### ISSUE TITLE
FastTrack-CLI.exe: Can't write tracking.db to the disk

### ISSUE THREAD

**Issue by mstimberg** [bgallois/FastTrack#59] opened 2023-11-21 13:27 UTC
Hi. We have been trying to run `FastTrack-CLI.exe` on Windows (it works without issue on Linux), and while it seems to successfully run the tracking itself, it fails to write the results database to disk:
```
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
QSqlDatabase: an instance of QCoreApplication is required for loading driver plugins
"Can't write tracking.db to the disk!"
Can't write tracking.db to the disk!
```
We've tried it on two different PCs, one with Windows 10 and one with Windows 11 (in both cases installed with the installer, since the portable folder does not come with `FastTrack-CLI.exe`).

Please let us know whether this is a known issue (ideally with a known solution :-) ), or whether there is anything else we can do to help with debugging. Thanks!

**Comment by bgallois** [comment] 2023-11-21 14:25
`FastTrack-CLI.exe` has its own portable archive; you can find it at [https://github.com/FastTrackOrg/FastTrack/releases/tag/v6.3.2](https://github.com/FastTrackOrg/FastTrack/releases/tag/v6.3.2). I will take a look, but the issue is most probably related to the `windeployqt` tool, which tends to be quite buggy with recent versions of Qt.

**Comment by mstimberg** [comment] 2023-11-21 14:28
> `FastTrack-CLI.exe` has its own portable archive; you can find it at https://github.com/FastTrackOrg/FastTrack/releases/tag/v6.3.2.

Ah, apologies, I had not seen that. Unfortunately, it shows the same error as the installer version.

**Comment by bgallois** [comment] 2023-11-21 15:40
[The latest continuous build](https://fasttrack.sh/download/Continuous/) is solving the problem. The fix will be included in the next stable version.

**Comment by mstimberg** [comment] 2023-11-21 16:14
Amazing, thanks for the quick fix ! From a quick test, I can confirm that the new version runs without an issue and creates the `tracking.db`.

**Closed as completed** 2023-11-22 20:37 UTC
Labels: bug, waiting_release, solved
